// src/components/CourseCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { BookOpen, Clock, Users, Star } from 'lucide-vue-next'

interface Course {
  id: string
  title: string
  description: string
  instructor: string
  instructorImage: string
  thumbnail: string
  category: string
  level: 'Beginner' | 'Intermediate' | 'Advanced'
  duration: number
  enrolledStudents: number
  rating: number
  modules: any[]
  price?: number
  enrolled?: boolean
  progress?: number
}

interface Props {
  course: Course
  showProgress?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  showProgress: false,
})

const instructorInitial = computed(() => props.course.instructor[0])
</script>

<template>
  <div
    class="overflow-hidden rounded-lg border bg-white shadow-sm transition-shadow hover:shadow-lg"
  >
    <!-- Thumbnail -->
    <RouterLink :to="`/course/${course.id}`">
      <div class="relative aspect-video overflow-hidden">
        <img
          :src="course.thumbnail"
          :alt="course.title"
          class="size-full object-cover transition-transform hover:scale-105"
        />
        <span
          class="absolute right-3 top-3 rounded-full bg-blue-600 px-3 py-1 text-xs font-medium text-white"
        >
          {{ course.level }}
        </span>
      </div>
    </RouterLink>

    <!-- Content -->
    <div class="p-4 space-y-3">
      <!-- Category and Rating -->
      <div class="flex items-center justify-between">
        <span class="rounded-full border px-3 py-1 text-xs font-medium">
          {{ course.category }}
        </span>
        <div class="flex items-center gap-1">
          <Star class="size-4 fill-yellow-400 text-yellow-400" />
          <span class="text-sm font-medium">{{ course.rating }}</span>
        </div>
      </div>

      <!-- Title -->
      <RouterLink :to="`/course/${course.id}`">
        <h3 class="line-clamp-2 text-lg font-semibold hover:text-blue-600">
          {{ course.title }}
        </h3>
      </RouterLink>

      <!-- Description -->
      <p class="line-clamp-2 text-sm text-gray-600">
        {{ course.description }}
      </p>

      <!-- Instructor -->
      <div class="flex items-center gap-2">
        <div class="flex size-8 items-center justify-center rounded-full bg-gray-200">
          <img
            v-if="course.instructorImage"
            :src="course.instructorImage"
            :alt="course.instructor"
            class="size-8 rounded-full object-cover"
          />
          <span v-else class="text-sm font-medium">{{ instructorInitial }}</span>
        </div>
        <span class="text-sm text-gray-600">{{ course.instructor }}</span>
      </div>

      <!-- Stats -->
      <div class="flex items-center justify-between text-sm text-gray-500">
        <div class="flex items-center gap-1">
          <Clock class="size-4" />
          <span>{{ course.duration }}h</span>
        </div>
        <div class="flex items-center gap-1">
          <Users class="size-4" />
          <span>{{ course.enrolledStudents.toLocaleString() }}</span>
        </div>
      </div>

      <!-- Progress Bar -->
      <div v-if="showProgress && course.enrolled" class="space-y-1">
        <div class="flex items-center justify-between text-sm">
          <span class="text-gray-600">Progress</span>
          <span class="font-medium">{{ course.progress }}%</span>
        </div>
        <div class="h-2 w-full overflow-hidden rounded-full bg-gray-200">
          <div
            class="h-full bg-blue-600 transition-all"
            :style="{ width: `${course.progress}%` }"
          ></div>
        </div>
      </div>
    </div>

    <!-- Footer Button -->
    <div class="border-t p-4">
      <RouterLink :to="`/course/${course.id}`" class="block">
        <button
          :class="[
            'w-full rounded-md px-4 py-2 text-sm font-medium transition-colors',
            course.enrolled
              ? 'bg-blue-600 text-white hover:bg-blue-700'
              : 'border border-gray-300 bg-white text-gray-700 hover:bg-gray-50',
          ]"
        >
          {{ course.enrolled ? 'Continue Learning' : 'View Course' }}
        </button>
      </RouterLink>
    </div>
  </div>
</template>

// Online Learning Management System/src/app/components/CourseCard.tsx
import { Link } from 'react-router';
import { Course } from '../types';
import { Card, CardContent, CardFooter, CardHeader } from './ui/card';
import { Badge } from './ui/badge';
import { Button } from './ui/button';
import { Clock, Users, Star } from 'lucide-react';
import { Progress } from './ui/progress';
import { Avatar, AvatarFallback, AvatarImage } from './ui/avatar';

interface CourseCardProps {
  course: Course;
  showProgress?: boolean;
}

export function CourseCard({ course, showProgress = false }: CourseCardProps) {
  return (
    <Card className="overflow-hidden transition-shadow hover:shadow-lg">
      <Link to={`/course/${course.id}`}>
        <div className="relative aspect-video overflow-hidden">
          <img
            src={course.thumbnail}
            alt={course.title}
            className="size-full object-cover transition-transform hover:scale-105"
          />
          <Badge className="absolute right-3 top-3">{course.level}</Badge>
        </div>
      </Link>

      <CardHeader className="space-y-2">
        <div className="flex items-center justify-between">
          <Badge variant="outline">{course.category}</Badge>
          <div className="flex items-center gap-1">
            <Star className="size-4 fill-yellow-400 text-yellow-400" />
            <span className="text-sm">{course.rating}</span>
          </div>
        </div>
        <Link to={`/course/${course.id}`}>
          <h3 className="line-clamp-2 text-lg hover:text-blue-600">
            {course.title}
          </h3>
        </Link>
        <p className="line-clamp-2 text-sm text-gray-600">
          {course.description}
        </p>
      </CardHeader>

      <CardContent className="space-y-3">
        <div className="flex items-center gap-2">
          <Avatar className="size-8">
            <AvatarImage src={course.instructorImage} />
            <AvatarFallback>{course.instructor[0]}</AvatarFallback>
          </Avatar>
          <span className="text-sm text-gray-600">{course.instructor}</span>
        </div>

        <div className="flex items-center justify-between text-sm text-gray-500">
          <div className="flex items-center gap-1">
            <Clock className="size-4" />
            <span>{course.duration}h</span>
          </div>
          <div className="flex items-center gap-1">
            <Users className="size-4" />
            <span>{course.enrolledStudents.toLocaleString()}</span>
          </div>
        </div>

        {showProgress && course.enrolled && (
          <div className="space-y-1">
            <div className="flex items-center justify-between text-sm">
              <span className="text-gray-600">Progress</span>
              <span className="font-medium">{course.progress}%</span>
            </div>
            <Progress value={course.progress} />
          </div>
        )}
      </CardContent>

      <CardFooter>
        {course.enrolled ? (
          <Link to={`/course/${course.id}`} className="w-full">
            <Button className="w-full">Continue Learning</Button>
          </Link>
        ) : (
          <Link to={`/course/${course.id}`} className="w-full">
            <Button className="w-full" variant="outline">
              View Course
            </Button>
          </Link>
        )}
      </CardFooter>
    </Card>
  );
}
