// src/components/QuizComponent.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { CheckCircle, XCircle, RotateCcw } from 'lucide-vue-next'
import type { QuizQuestion } from '@/types'

interface Props {
  questions: QuizQuestion[]
}

const props = defineProps<Props>()
const emit = defineEmits<{
  complete: [score: number]
}>()

const currentQuestionIndex = ref(0)
const selectedAnswers = ref<number[]>([])
const showResults = ref(false)
const quizCompleted = ref(false)

const currentQuestion = computed(() => props.questions[currentQuestionIndex.value])
const progress = computed(() => ((currentQuestionIndex.value + 1) / props.questions.length) * 100)

const score = computed(() => {
  return props.questions.reduce((acc, q, idx) => {
    return acc + (selectedAnswers.value[idx] === q.correctAnswer ? 1 : 0)
  }, 0)
})

const percentage = computed(() => Math.round((score.value / props.questions.length) * 100))

function selectAnswer(optionIndex: number) {
  selectedAnswers.value[currentQuestionIndex.value] = optionIndex
}

function nextQuestion() {
  if (currentQuestionIndex.value < props.questions.length - 1) {
    currentQuestionIndex.value++
  } else {
    showResults.value = true
  }
}

function previousQuestion() {
  if (currentQuestionIndex.value > 0) {
    currentQuestionIndex.value--
  }
}

function submitQuiz() {
  quizCompleted.value = true
  emit('complete', percentage.value)
}

function retakeQuiz() {
  currentQuestionIndex.value = 0
  selectedAnswers.value = []
  showResults.value = false
  quizCompleted.value = false
}
</script>

<template>
  <div class="mx-auto max-w-3xl space-y-6">
    <!-- Quiz Header -->
    <div v-if="!showResults" class="space-y-2">
      <div class="flex items-center justify-between">
        <h3 class="text-lg font-semibold">
          Question {{ currentQuestionIndex + 1 }} of {{ questions.length }}
        </h3>
        <span class="text-sm text-gray-600">{{ Math.round(progress) }}% Complete</span>
      </div>
      <div class="h-2 w-full overflow-hidden rounded-full bg-gray-200">
        <div class="h-full bg-blue-600 transition-all" :style="{ width: `${progress}%` }"></div>
      </div>
    </div>

    <!-- Question -->
    <div v-if="!showResults" class="rounded-lg border bg-white p-6 shadow-sm">
      <h4 class="mb-6 text-xl font-medium">{{ currentQuestion.question }}</h4>

      <div class="space-y-3">
        <button
          v-for="(option, index) in currentQuestion.options"
          :key="index"
          @click="selectAnswer(index)"
          :class="[
            'w-full rounded-lg border-2 p-4 text-left transition-all',
            selectedAnswers[currentQuestionIndex] === index
              ? 'border-blue-600 bg-blue-50'
              : 'border-gray-200 hover:border-gray-300',
          ]"
        >
          <div class="flex items-center gap-3">
            <div
              :class="[
                'flex size-6 items-center justify-center rounded-full border-2',
                selectedAnswers[currentQuestionIndex] === index
                  ? 'border-blue-600 bg-blue-600'
                  : 'border-gray-300',
              ]"
            >
              <div
                v-if="selectedAnswers[currentQuestionIndex] === index"
                class="size-3 rounded-full bg-white"
              ></div>
            </div>
            <span>{{ option }}</span>
          </div>
        </button>
      </div>

      <!-- Navigation -->
      <div class="mt-6 flex items-center justify-between">
        <button
          @click="previousQuestion"
          :disabled="currentQuestionIndex === 0"
          class="rounded-md border px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
        >
          Previous
        </button>
        <button
          @click="nextQuestion"
          :disabled="selectedAnswers[currentQuestionIndex] === undefined"
          class="rounded-md bg-blue-600 px-6 py-2 text-sm font-medium text-white transition-colors hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
        >
          {{ currentQuestionIndex === questions.length - 1 ? 'Review Answers' : 'Next' }}
        </button>
      </div>
    </div>

    <!-- Results -->
    <div v-else class="space-y-6">
      <!-- Score Card -->
      <div class="rounded-lg border bg-white p-8 text-center shadow-sm">
        <div
          :class="[
            'mx-auto mb-4 flex size-24 items-center justify-center rounded-full',
            percentage >= 70 ? 'bg-green-100' : 'bg-red-100',
          ]"
        >
          <span
            :class="['text-3xl font-bold', percentage >= 70 ? 'text-green-600' : 'text-red-600']"
          >
            {{ percentage }}%
          </span>
        </div>
        <h3 class="mb-2 text-2xl font-bold">
          {{ percentage >= 70 ? 'Great Job!' : 'Keep Practicing!' }}
        </h3>
        <p class="text-gray-600">
          You scored {{ score }} out of {{ questions.length }} questions correctly
        </p>
      </div>

      <!-- Answer Review -->
      <div class="space-y-4">
        <h4 class="text-lg font-semibold">Review Your Answers</h4>
        <div
          v-for="(question, index) in questions"
          :key="index"
          class="rounded-lg border bg-white p-6 shadow-sm"
        >
          <div class="mb-4 flex items-start gap-3">
            <component
              :is="selectedAnswers[index] === question.correctAnswer ? CheckCircle : XCircle"
              :class="[
                'size-6 flex-shrink-0',
                selectedAnswers[index] === question.correctAnswer
                  ? 'text-green-600'
                  : 'text-red-600',
              ]"
            />
            <div class="flex-1">
              <h5 class="mb-2 font-medium">{{ question.question }}</h5>
              <div class="space-y-2 text-sm">
                <p>
                  <span class="font-medium">Your answer:</span>
                  <span
                    :class="
                      selectedAnswers[index] === question.correctAnswer
                        ? 'text-green-600'
                        : 'text-red-600'
                    "
                  >
                    {{ question.options[selectedAnswers[index]] }}
                  </span>
                </p>
                <p v-if="selectedAnswers[index] !== question.correctAnswer">
                  <span class="font-medium">Correct answer:</span>
                  <span class="text-green-600">
                    {{ question.options[question.correctAnswer] }}
                  </span>
                </p>
                <p v-if="question.explanation" class="text-gray-600">
                  <span class="font-medium">Explanation:</span>
                  {{ question.explanation }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Actions -->
      <div class="flex gap-4">
        <button
          @click="retakeQuiz"
          class="flex items-center gap-2 rounded-md border px-6 py-2 text-sm font-medium transition-colors hover:bg-gray-50"
        >
          <RotateCcw class="size-4" />
          Retake Quiz
        </button>
        <button
          v-if="!quizCompleted"
          @click="submitQuiz"
          class="rounded-md bg-blue-600 px-6 py-2 text-sm font-medium text-white transition-colors hover:bg-blue-700"
        >
          Complete Lesson
        </button>
      </div>
    </div>
  </div>
</template>

// Online Learning Management System/src/app/components/QuizComponent.tsx
import { useState } from 'react';
import { QuizQuestion } from '../types';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Button } from './ui/button';
import { RadioGroup, RadioGroupItem } from './ui/radio-group';
import { Label } from './ui/label';
import { Alert, AlertDescription } from './ui/alert';
import { CheckCircle2, XCircle, Trophy } from 'lucide-react';
import { Progress } from './ui/progress';

interface QuizComponentProps {
  questions: QuizQuestion[];
  onComplete: (score: number, passed: boolean) => void;
}

export function QuizComponent({ questions, onComplete }: QuizComponentProps) {
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
  const [showFeedback, setShowFeedback] = useState(false);
  const [answers, setAnswers] = useState<number[]>([]);
  const [quizCompleted, setQuizCompleted] = useState(false);

  const question = questions[currentQuestion];
  const progress = ((currentQuestion + 1) / questions.length) * 100;

  const handleSubmitAnswer = () => {
    if (selectedAnswer === null) return;

    setShowFeedback(true);
    setAnswers([...answers, selectedAnswer]);
  };

  const handleNextQuestion = () => {
    if (currentQuestion < questions.length - 1) {
      setCurrentQuestion(currentQuestion + 1);
      setSelectedAnswer(null);
      setShowFeedback(false);
    } else {
      // Quiz completed
      const finalAnswers = [...answers, selectedAnswer!];
      const correctCount = finalAnswers.reduce((count, answer, index) => {
        return count + (answer === questions[index].correctAnswer ? 1 : 0);
      }, 0);
      const score = Math.round((correctCount / questions.length) * 100);
      const passed = score >= 70; // 70% passing grade

      setQuizCompleted(true);
      onComplete(score, passed);
    }
  };

  const handleRetry = () => {
    setCurrentQuestion(0);
    setSelectedAnswer(null);
    setShowFeedback(false);
    setAnswers([]);
    setQuizCompleted(false);
  };

  if (quizCompleted) {
    const correctCount = answers.reduce((count, answer, index) => {
      return count + (answer === questions[index].correctAnswer ? 1 : 0);
    }, 0);
    const score = Math.round((correctCount / questions.length) * 100);
    const passed = score >= 70;

    return (
      <Card>
        <CardContent className="p-8 text-center">
          <div className={`mx-auto mb-4 flex size-20 items-center justify-center rounded-full ${
            passed ? 'bg-green-100' : 'bg-red-100'
          }`}>
            {passed ? (
              <Trophy className="size-10 text-green-600" />
            ) : (
              <XCircle className="size-10 text-red-600" />
            )}
          </div>
          <h2 className="mb-2 text-2xl">
            {passed ? 'Congratulations!' : 'Quiz Not Passed'}
          </h2>
          <p className="mb-6 text-gray-600">
            You scored {correctCount} out of {questions.length} ({score}%)
          </p>
          {passed ? (
            <p className="text-green-600 mb-6">
              Great job! You've passed the quiz.
            </p>
          ) : (
            <p className="text-red-600 mb-6">
              You need 70% to pass. Review the material and try again.
            </p>
          )}
          <Button onClick={handleRetry} variant={passed ? 'outline' : 'default'}>
            {passed ? 'Retake Quiz' : 'Try Again'}
          </Button>
        </CardContent>
      </Card>
    );
  }

  const isCorrect = selectedAnswer === question.correctAnswer;

  return (
    <Card>
      <CardHeader>
        <div className="space-y-2">
          <div className="flex items-center justify-between text-sm text-gray-600">
            <span>Question {currentQuestion + 1} of {questions.length}</span>
            <span>{Math.round(progress)}%</span>
          </div>
          <Progress value={progress} />
        </div>
        <CardTitle className="mt-4">{question.question}</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        <RadioGroup
          value={selectedAnswer?.toString()}
          onValueChange={(value) => setSelectedAnswer(parseInt(value))}
          disabled={showFeedback}
        >
          <div className="space-y-3">
            {question.options.map((option, index) => (
              <div
                key={index}
                className={`flex items-center space-x-2 rounded-lg border p-4 transition-colors ${
                  showFeedback
                    ? index === question.correctAnswer
                      ? 'border-green-500 bg-green-50'
                      : index === selectedAnswer && !isCorrect
                      ? 'border-red-500 bg-red-50'
                      : ''
                    : 'hover:bg-gray-50'
                }`}
              >
                <RadioGroupItem value={index.toString()} id={`option-${index}`} />
                <Label
                  htmlFor={`option-${index}`}
                  className="flex-1 cursor-pointer"
                >
                  {option}
                </Label>
                {showFeedback && index === question.correctAnswer && (
                  <CheckCircle2 className="size-5 text-green-600" />
                )}
                {showFeedback && index === selectedAnswer && !isCorrect && (
                  <XCircle className="size-5 text-red-600" />
                )}
              </div>
            ))}
          </div>
        </RadioGroup>

        {showFeedback && question.explanation && (
          <Alert className={isCorrect ? 'border-green-500' : 'border-red-500'}>
            <AlertDescription>
              <strong>{isCorrect ? 'Correct!' : 'Incorrect.'}</strong> {question.explanation}
            </AlertDescription>
          </Alert>
        )}

        <div className="flex justify-end gap-3">
          {!showFeedback ? (
            <Button
              onClick={handleSubmitAnswer}
              disabled={selectedAnswer === null}
            >
              Submit Answer
            </Button>
          ) : (
            <Button onClick={handleNextQuestion}>
              {currentQuestion < questions.length - 1 ? 'Next Question' : 'Finish Quiz'}
            </Button>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
