// Online Learning Management System/src/app/components/NotesPanel.tsx
import { useState } from 'react';
import { Note } from '../types';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Button } from './ui/button';
import { Textarea } from './ui/textarea';
import { StickyNote, Plus, Trash2 } from 'lucide-react';

interface NotesPanelProps {
  notes: Note[];
  onAddNote: (content: string) => void;
  onDeleteNote: (noteId: string) => void;
}

export function NotesPanel({ notes, onAddNote, onDeleteNote }: NotesPanelProps) {
  const [showNoteForm, setShowNoteForm] = useState(false);
  const [newNoteContent, setNewNoteContent] = useState('');

  const handleSubmitNote = () => {
    if (newNoteContent.trim()) {
      onAddNote(newNoteContent);
      setNewNoteContent('');
      setShowNoteForm(false);
    }
  };

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const formatDate = (date: Date) => {
    return new Date(date).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <StickyNote className="size-5" />
            My Notes
          </CardTitle>
          {!showNoteForm && (
            <Button
              size="sm"
              variant="outline"
              onClick={() => setShowNoteForm(true)}
              className="gap-2"
            >
              <Plus className="size-4" />
              Add Note
            </Button>
          )}
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Note Form */}
        {showNoteForm && (
          <div className="space-y-3 rounded-lg border p-3">
            <Textarea
              value={newNoteContent}
              onChange={(e) => setNewNoteContent(e.target.value)}
              placeholder="Write your note here..."
              rows={3}
              autoFocus
            />
            <div className="flex gap-2 justify-end">
              <Button
                size="sm"
                variant="outline"
                onClick={() => {
                  setShowNoteForm(false);
                  setNewNoteContent('');
                }}
              >
                Cancel
              </Button>
              <Button
                size="sm"
                onClick={handleSubmitNote}
                disabled={!newNoteContent.trim()}
              >
                Save Note
              </Button>
            </div>
          </div>
        )}

        {/* Notes List */}
        <div className="space-y-3">
          {notes.length === 0 ? (
            <div className="rounded-lg border border-dashed p-8 text-center">
              <StickyNote className="mx-auto mb-2 size-8 text-gray-400" />
              <p className="text-sm text-gray-600">No notes yet</p>
              <p className="text-xs text-gray-500">
                Take notes to remember key points
              </p>
            </div>
          ) : (
            notes.map((note) => (
              <div
                key={note.id}
                className="group rounded-lg border p-3 transition-shadow hover:shadow-md"
              >
                <div className="mb-2 flex items-start justify-between">
                  <span className="rounded bg-blue-100 px-2 py-0.5 text-xs text-blue-700">
                    {formatTime(note.timestamp)}
                  </span>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="opacity-0 group-hover:opacity-100 h-6 w-6 p-0"
                    onClick={() => onDeleteNote(note.id)}
                  >
                    <Trash2 className="size-3 text-red-600" />
                  </Button>
                </div>
                <p className="text-sm text-gray-700">{note.content}</p>
                <p className="mt-2 text-xs text-gray-500">
                  {formatDate(note.createdAt)}
                </p>
              </div>
            ))
          )}
        </div>
      </CardContent>
    </Card>
  );
}

// src/components/NotesPanel.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { Plus, Trash2, Clock } from 'lucide-vue-next'
import type { Note } from '@/types'

interface Props {
  courseId: string
  lessonId: string
  notes: Note[]
}

const props = defineProps<Props>()
const emit = defineEmits<{
  addNote: [content: string, timestamp: number]
  deleteNote: [noteId: string]
}>()

const newNoteContent = ref('')
const currentTimestamp = ref(0)

const lessonNotes = computed(() => {
  return props.notes
    .filter((n) => n.courseId === props.courseId && n.lessonId === props.lessonId)
    .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
})

function addNote() {
  if (newNoteContent.value.trim()) {
    emit('addNote', newNoteContent.value.trim(), currentTimestamp.value)
    newNoteContent.value = ''
  }
}

function deleteNote(noteId: string) {
  emit('deleteNote', noteId)
}

function formatTime(seconds: number): string {
  const mins = Math.floor(seconds / 60)
  const secs = Math.floor(seconds % 60)
  return `${mins}:${secs.toString().padStart(2, '0')}`
}

function formatDate(date: Date): string {
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  }).format(date)
}

defineExpose({
  setCurrentTimestamp: (time: number) => {
    currentTimestamp.value = time
  },
})
</script>

<template>
  <div class="flex h-full flex-col rounded-lg border bg-white shadow-sm">
    <!-- Header -->
    <div class="border-b p-4">
      <h3 class="text-lg font-semibold">Lesson Notes</h3>
      <p class="text-sm text-gray-600">{{ lessonNotes.length }} notes</p>
    </div>

    <!-- Notes List -->
    <div class="flex-1 space-y-3 overflow-y-auto p-4">
      <div
        v-if="lessonNotes.length === 0"
        class="flex h-full items-center justify-center text-center text-gray-500"
      >
        <div>
          <p class="mb-2 text-sm">No notes yet</p>
          <p class="text-xs">Add notes to remember important points</p>
        </div>
      </div>

      <div
        v-for="note in lessonNotes"
        :key="note.id"
        class="group rounded-lg border bg-gray-50 p-3 transition-colors hover:bg-gray-100"
      >
        <div class="mb-2 flex items-start justify-between gap-2">
          <div class="flex items-center gap-2 text-xs text-gray-600">
            <Clock class="size-3" />
            <span>{{ formatTime(note.timestamp) }}</span>
            <span>•</span>
            <span>{{ formatDate(note.createdAt) }}</span>
          </div>
          <button
            @click="deleteNote(note.id)"
            class="opacity-0 transition-opacity group-hover:opacity-100"
          >
            <Trash2 class="size-4 text-red-600 hover:text-red-700" />
          </button>
        </div>
        <p class="text-sm">{{ note.content }}</p>
      </div>
    </div>

    <!-- Add Note Form -->
    <div class="border-t p-4">
      <div class="space-y-2">
        <textarea
          v-model="newNoteContent"
          placeholder="Add a note at current timestamp..."
          rows="3"
          class="w-full resize-none rounded-md border p-2 text-sm focus:border-blue-600 focus:outline-none focus:ring-1 focus:ring-blue-600"
          @keydown.ctrl.enter="addNote"
        ></textarea>
        <div class="flex items-center justify-between">
          <span class="text-xs text-gray-500">Ctrl+Enter to save</span>
          <button
            @click="addNote"
            :disabled="!newNoteContent.trim()"
            class="flex items-center gap-2 rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Plus class="size-4" />
            Add Note
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
